### ISSUE TITLE
index range incorrect

### ISSUE THREAD

**Issue by jhalliday** [shojinishimura/Tiny-MD-HBase#1]
$ bin/hbase tiny.mdhbase.Client put 10 10 101
$ bin/hbase tiny.mdhbase.Client get 10 10
[101, (10,10)]
$ bin/hbase tiny.mdhbase.Client count 0 0 2147483647 2147483647
Query Region: [(0,0), (2147483647,2147483647)]
1 hits
$ bin/hbase tiny.mdhbase.Client count 1 1 2147483647 2147483647
Query Region: [(1,1), (2147483647,2147483647)]
0 hits

Index.findBucketsInRange():
byte[] startKey = Utils.bitwiseZip(rx.min, ry.min);
is incorrect, since the bucket starts _below_ the points it contains.

byte[] probeKey = Utils.bitwiseZip(rx.min, ry.min);
Result bucketEntry = indexTable.getRowOrBefore(probeKey, FAMILY_INFO);
byte[] startKey = bucketEntry.getRow();

may work, but at the cost of an additional round trip.

**Comment by shojinishimura** [comment]
jhalliday

Thank you for your report.
You're right.
I fixed it according to your report.
